name: ci

on:
  push:
    branches:
      - 'remove-cachepot'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          file: ./Dockerfile.lel
          tags: user/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
